sources:
  - Young-Serif.glyphs
axisOrder:
  - wght
  - ital
familyName: "Young Serif"
cleanUp: true
buildVariable: true
buildStatic: true
buildTTF: true
buildOTF: true
buildSmallCap: false
autohintTTF: true
includeSourceFixes: true
